version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=src/interfaces/web/app.py